from __future__ import annotations

from .models import Supplier, SKU, Location, InventoryRecord, SaleRecord


def sample_suppliers() -> list[Supplier]:
    return [
        Supplier(
            supplier_id="SUP-RED",
            name="Red Label Supplier",
            lead_time_days=5,
            min_order_qty=80,
            price_band={
                "SKU-RED-TEA": 1.1,
                "SKU-MASALA": 1.5,
                "SKU-BLACK-TEA": 1.2,
            },
        ),
        Supplier(
            supplier_id="SUP-GROC",
            name="Grocer Partner",
            lead_time_days=7,
            min_order_qty=150,
            price_band={
                "SKU-RICE": 0.9,
                "SKU-PULSES": 1.2,
                "SKU-FLOUR": 0.8,
                "SKU-GHEE": 3.5,
            },
        ),
        Supplier(
            supplier_id="SUP-FRESH",
            name="Fresh Farms",
            lead_time_days=4,
            min_order_qty=70,
            price_band={
                "SKU-OLIVE-OIL": 4.8,
                "SKU-HONEY": 2.9,
                "SKU-DRIED-FRUIT": 3.4,
            },
        ),
        Supplier(
            supplier_id="SUP-BEV",
            name="Beverage Co",
            lead_time_days=6,
            min_order_qty=100,
            price_band={
                "SKU-ORANGE-JUICE": 2.1,
                "SKU-SPARKLING": 1.9,
                "SKU-COLD-BREW": 2.8,
            },
        ),
        Supplier(
            supplier_id="SUP-SNACK",
            name="Snack Junction",
            lead_time_days=5,
            min_order_qty=90,
            price_band={
                "SKU-TRAIL-MIX": 3.1,
                "SKU-CHIPS": 1.2,
                "SKU-COOKIES": 2.0,
                "SKU-GRANOLA": 2.4,
            },
        ),
        Supplier(
            supplier_id="SUP-HOUSE",
            name="Home Essentials",
            lead_time_days=6,
            min_order_qty=110,
            price_band={
                "SKU-DETERGENT": 5.0,
                "SKU-DISH-SOAP": 2.2,
                "SKU-PAPER-TOWEL": 4.5,
                "SKU-SOAP": 1.1,
            },
        ),
    ]


def sample_skus() -> list[SKU]:
    return [
        SKU(sku="SKU-RED-TEA", supplier_id="SUP-RED", case_size=10),
        SKU(sku="SKU-MASALA", supplier_id="SUP-RED", case_size=12),
        SKU(sku="SKU-BLACK-TEA", supplier_id="SUP-RED", case_size=10),
        SKU(sku="SKU-RICE", supplier_id="SUP-GROC", case_size=20),
        SKU(sku="SKU-PULSES", supplier_id="SUP-GROC", case_size=24),
        SKU(sku="SKU-FLOUR", supplier_id="SUP-GROC", case_size=15),
        SKU(sku="SKU-GHEE", supplier_id="SUP-GROC", case_size=8),
        SKU(sku="SKU-OLIVE-OIL", supplier_id="SUP-FRESH", case_size=6),
        SKU(sku="SKU-HONEY", supplier_id="SUP-FRESH", case_size=12),
        SKU(sku="SKU-DRIED-FRUIT", supplier_id="SUP-FRESH", case_size=10),
        SKU(sku="SKU-ORANGE-JUICE", supplier_id="SUP-BEV", case_size=12),
        SKU(sku="SKU-SPARKLING", supplier_id="SUP-BEV", case_size=24),
        SKU(sku="SKU-COLD-BREW", supplier_id="SUP-BEV", case_size=12),
        SKU(sku="SKU-TRAIL-MIX", supplier_id="SUP-SNACK", case_size=18),
        SKU(sku="SKU-CHIPS", supplier_id="SUP-SNACK", case_size=24),
        SKU(sku="SKU-COOKIES", supplier_id="SUP-SNACK", case_size=20),
        SKU(sku="SKU-GRANOLA", supplier_id="SUP-SNACK", case_size=16),
        SKU(sku="SKU-DETERGENT", supplier_id="SUP-HOUSE", case_size=12),
        SKU(sku="SKU-DISH-SOAP", supplier_id="SUP-HOUSE", case_size=12),
        SKU(sku="SKU-PAPER-TOWEL", supplier_id="SUP-HOUSE", case_size=6),
        SKU(sku="SKU-SOAP", supplier_id="SUP-HOUSE", case_size=24),
    ]


def sample_locations() -> list[Location]:
    return [
        Location(location_id="DC-EAST", kind="dc", capacity=6200, safety_stock=170),
        Location(location_id="DC-WEST", kind="dc", capacity=5900, safety_stock=160),
        Location(location_id="STORE-NY", kind="store", capacity=950, safety_stock=55),
        Location(location_id="STORE-SF", kind="store", capacity=920, safety_stock=50),
        Location(location_id="STORE-CHI", kind="store", capacity=900, safety_stock=50),
        Location(location_id="STORE-DAL", kind="store", capacity=880, safety_stock=45),
        Location(location_id="ONLINE", kind="online", capacity=1600, safety_stock=90),
    ]


def sample_inventory() -> list[InventoryRecord]:
    rows = [
        ("SKU-RED-TEA", "DC-EAST", 340, 60),
        ("SKU-RED-TEA", "DC-WEST", 210, 0),
        ("SKU-RED-TEA", "STORE-NY", 80, 0),
        ("SKU-RED-TEA", "STORE-SF", 60, 0),
        ("SKU-RED-TEA", "STORE-CHI", 65, 0),
        ("SKU-RED-TEA", "STORE-DAL", 62, 0),
        ("SKU-RED-TEA", "ONLINE", 90, 20),
        ("SKU-MASALA", "DC-EAST", 250, 20),
        ("SKU-MASALA", "DC-WEST", 170, 0),
        ("SKU-MASALA", "STORE-NY", 70, 0),
        ("SKU-MASALA", "STORE-SF", 55, 0),
        ("SKU-MASALA", "STORE-CHI", 58, 0),
        ("SKU-MASALA", "STORE-DAL", 54, 0),
        ("SKU-MASALA", "ONLINE", 55, 0),
        ("SKU-BLACK-TEA", "DC-EAST", 270, 30),
        ("SKU-BLACK-TEA", "DC-WEST", 180, 20),
        ("SKU-BLACK-TEA", "STORE-NY", 52, 0),
        ("SKU-BLACK-TEA", "STORE-SF", 45, 0),
        ("SKU-BLACK-TEA", "STORE-CHI", 42, 0),
        ("SKU-BLACK-TEA", "STORE-DAL", 40, 0),
        ("SKU-BLACK-TEA", "ONLINE", 65, 10),
        ("SKU-RICE", "DC-EAST", 980, 180),
        ("SKU-RICE", "DC-WEST", 740, 140),
        ("SKU-RICE", "STORE-NY", 110, 0),
        ("SKU-RICE", "STORE-SF", 95, 0),
        ("SKU-RICE", "STORE-CHI", 100, 0),
        ("SKU-RICE", "STORE-DAL", 98, 0),
        ("SKU-RICE", "ONLINE", 130, 0),
        ("SKU-PULSES", "DC-EAST", 480, 0),
        ("SKU-PULSES", "DC-WEST", 360, 70),
        ("SKU-PULSES", "STORE-NY", 84, 0),
        ("SKU-PULSES", "STORE-SF", 72, 0),
        ("SKU-PULSES", "STORE-CHI", 76, 0),
        ("SKU-PULSES", "STORE-DAL", 70, 0),
        ("SKU-PULSES", "ONLINE", 90, 0),
        ("SKU-FLOUR", "DC-EAST", 540, 100),
        ("SKU-FLOUR", "DC-WEST", 380, 80),
        ("SKU-FLOUR", "STORE-NY", 78, 0),
        ("SKU-FLOUR", "STORE-SF", 70, 0),
        ("SKU-FLOUR", "STORE-CHI", 72, 0),
        ("SKU-FLOUR", "STORE-DAL", 68, 0),
        ("SKU-FLOUR", "ONLINE", 92, 0),
        ("SKU-GHEE", "DC-EAST", 200, 40),
        ("SKU-GHEE", "DC-WEST", 150, 25),
        ("SKU-GHEE", "STORE-NY", 32, 0),
        ("SKU-GHEE", "STORE-SF", 28, 0),
        ("SKU-GHEE", "STORE-CHI", 30, 0),
        ("SKU-GHEE", "STORE-DAL", 26, 0),
        ("SKU-GHEE", "ONLINE", 34, 0),
        ("SKU-OLIVE-OIL", "DC-EAST", 160, 30),
        ("SKU-OLIVE-OIL", "DC-WEST", 120, 20),
        ("SKU-OLIVE-OIL", "STORE-NY", 28, 0),
        ("SKU-OLIVE-OIL", "STORE-SF", 24, 0),
        ("SKU-OLIVE-OIL", "STORE-CHI", 24, 0),
        ("SKU-OLIVE-OIL", "STORE-DAL", 22, 0),
        ("SKU-OLIVE-OIL", "ONLINE", 32, 0),
        ("SKU-HONEY", "DC-EAST", 170, 25),
        ("SKU-HONEY", "DC-WEST", 130, 20),
        ("SKU-HONEY", "STORE-NY", 30, 0),
        ("SKU-HONEY", "STORE-SF", 28, 0),
        ("SKU-HONEY", "STORE-CHI", 26, 0),
        ("SKU-HONEY", "STORE-DAL", 24, 0),
        ("SKU-HONEY", "ONLINE", 36, 0),
        ("SKU-DRIED-FRUIT", "DC-EAST", 190, 30),
        ("SKU-DRIED-FRUIT", "DC-WEST", 150, 25),
        ("SKU-DRIED-FRUIT", "STORE-NY", 40, 0),
        ("SKU-DRIED-FRUIT", "STORE-SF", 34, 0),
        ("SKU-DRIED-FRUIT", "STORE-CHI", 32, 0),
        ("SKU-DRIED-FRUIT", "STORE-DAL", 30, 0),
        ("SKU-DRIED-FRUIT", "ONLINE", 42, 0),
        ("SKU-ORANGE-JUICE", "DC-EAST", 260, 60),
        ("SKU-ORANGE-JUICE", "DC-WEST", 210, 40),
        ("SKU-ORANGE-JUICE", "STORE-NY", 56, 0),
        ("SKU-ORANGE-JUICE", "STORE-SF", 48, 0),
        ("SKU-ORANGE-JUICE", "STORE-CHI", 46, 0),
        ("SKU-ORANGE-JUICE", "STORE-DAL", 44, 0),
        ("SKU-ORANGE-JUICE", "ONLINE", 60, 0),
        ("SKU-SPARKLING", "DC-EAST", 320, 90),
        ("SKU-SPARKLING", "DC-WEST", 260, 60),
        ("SKU-SPARKLING", "STORE-NY", 74, 0),
        ("SKU-SPARKLING", "STORE-SF", 64, 0),
        ("SKU-SPARKLING", "STORE-CHI", 62, 0),
        ("SKU-SPARKLING", "STORE-DAL", 60, 0),
        ("SKU-SPARKLING", "ONLINE", 82, 0),
        ("SKU-COLD-BREW", "DC-EAST", 220, 50),
        ("SKU-COLD-BREW", "DC-WEST", 180, 40),
        ("SKU-COLD-BREW", "STORE-NY", 50, 0),
        ("SKU-COLD-BREW", "STORE-SF", 44, 0),
        ("SKU-COLD-BREW", "STORE-CHI", 42, 0),
        ("SKU-COLD-BREW", "STORE-DAL", 40, 0),
        ("SKU-COLD-BREW", "ONLINE", 58, 0),
        ("SKU-TRAIL-MIX", "DC-EAST", 240, 40),
        ("SKU-TRAIL-MIX", "DC-WEST", 190, 30),
        ("SKU-TRAIL-MIX", "STORE-NY", 46, 0),
        ("SKU-TRAIL-MIX", "STORE-SF", 40, 0),
        ("SKU-TRAIL-MIX", "STORE-CHI", 38, 0),
        ("SKU-TRAIL-MIX", "STORE-DAL", 36, 0),
        ("SKU-TRAIL-MIX", "ONLINE", 52, 0),
        ("SKU-CHIPS", "DC-EAST", 260, 50),
        ("SKU-CHIPS", "DC-WEST", 200, 40),
        ("SKU-CHIPS", "STORE-NY", 62, 0),
        ("SKU-CHIPS", "STORE-SF", 54, 0),
        ("SKU-CHIPS", "STORE-CHI", 50, 0),
        ("SKU-CHIPS", "STORE-DAL", 48, 0),
        ("SKU-CHIPS", "ONLINE", 66, 0),
        ("SKU-COOKIES", "DC-EAST", 230, 40),
        ("SKU-COOKIES", "DC-WEST", 180, 30),
        ("SKU-COOKIES", "STORE-NY", 56, 0),
        ("SKU-COOKIES", "STORE-SF", 48, 0),
        ("SKU-COOKIES", "STORE-CHI", 46, 0),
        ("SKU-COOKIES", "STORE-DAL", 44, 0),
        ("SKU-COOKIES", "ONLINE", 64, 0),
        ("SKU-GRANOLA", "DC-EAST", 210, 35),
        ("SKU-GRANOLA", "DC-WEST", 170, 30),
        ("SKU-GRANOLA", "STORE-NY", 44, 0),
        ("SKU-GRANOLA", "STORE-SF", 38, 0),
        ("SKU-GRANOLA", "STORE-CHI", 36, 0),
        ("SKU-GRANOLA", "STORE-DAL", 34, 0),
        ("SKU-GRANOLA", "ONLINE", 50, 0),
        ("SKU-DETERGENT", "DC-EAST", 210, 40),
        ("SKU-DETERGENT", "DC-WEST", 170, 30),
        ("SKU-DETERGENT", "STORE-NY", 44, 0),
        ("SKU-DETERGENT", "STORE-SF", 38, 0),
        ("SKU-DETERGENT", "STORE-CHI", 36, 0),
        ("SKU-DETERGENT", "STORE-DAL", 34, 0),
        ("SKU-DETERGENT", "ONLINE", 50, 0),
        ("SKU-DISH-SOAP", "DC-EAST", 190, 35),
        ("SKU-DISH-SOAP", "DC-WEST", 150, 25),
        ("SKU-DISH-SOAP", "STORE-NY", 40, 0),
        ("SKU-DISH-SOAP", "STORE-SF", 34, 0),
        ("SKU-DISH-SOAP", "STORE-CHI", 32, 0),
        ("SKU-DISH-SOAP", "STORE-DAL", 30, 0),
        ("SKU-DISH-SOAP", "ONLINE", 46, 0),
        ("SKU-PAPER-TOWEL", "DC-EAST", 260, 50),
        ("SKU-PAPER-TOWEL", "DC-WEST", 210, 40),
        ("SKU-PAPER-TOWEL", "STORE-NY", 48, 0),
        ("SKU-PAPER-TOWEL", "STORE-SF", 42, 0),
        ("SKU-PAPER-TOWEL", "STORE-CHI", 40, 0),
        ("SKU-PAPER-TOWEL", "STORE-DAL", 38, 0),
        ("SKU-PAPER-TOWEL", "ONLINE", 58, 0),
        ("SKU-SOAP", "DC-EAST", 230, 40),
        ("SKU-SOAP", "DC-WEST", 180, 30),
        ("SKU-SOAP", "STORE-NY", 54, 0),
        ("SKU-SOAP", "STORE-SF", 46, 0),
        ("SKU-SOAP", "STORE-CHI", 44, 0),
        ("SKU-SOAP", "STORE-DAL", 42, 0),
        ("SKU-SOAP", "ONLINE", 62, 0),
    ]
    return [InventoryRecord(sku, location_id, on_hand=on_hand, inbound=inbound) for sku, location_id, on_hand, inbound in rows]


def sample_sales() -> list[SaleRecord]:
    rows = [
        ("SKU-RED-TEA", "STORE-NY", 190, 14),
        ("SKU-RED-TEA", "STORE-SF", 150, 14),
        ("SKU-RED-TEA", "STORE-CHI", 140, 14),
        ("SKU-RED-TEA", "STORE-DAL", 135, 14),
        ("SKU-RED-TEA", "ONLINE", 240, 14),
        ("SKU-MASALA", "STORE-NY", 120, 14),
        ("SKU-MASALA", "STORE-SF", 95, 14),
        ("SKU-MASALA", "STORE-CHI", 92, 14),
        ("SKU-MASALA", "STORE-DAL", 88, 14),
        ("SKU-MASALA", "ONLINE", 170, 14),
        ("SKU-BLACK-TEA", "STORE-NY", 100, 14),
        ("SKU-BLACK-TEA", "STORE-SF", 88, 14),
        ("SKU-BLACK-TEA", "STORE-CHI", 82, 14),
        ("SKU-BLACK-TEA", "STORE-DAL", 78, 14),
        ("SKU-BLACK-TEA", "ONLINE", 180, 14),
        ("SKU-RICE", "DC-EAST", 560, 14),
        ("SKU-RICE", "DC-WEST", 480, 14),
        ("SKU-RICE", "STORE-NY", 150, 14),
        ("SKU-RICE", "STORE-SF", 130, 14),
        ("SKU-RICE", "STORE-DAL", 140, 14),
        ("SKU-RICE", "ONLINE", 200, 14),
        ("SKU-PULSES", "DC-EAST", 330, 14),
        ("SKU-PULSES", "DC-WEST", 260, 14),
        ("SKU-PULSES", "STORE-NY", 110, 14),
        ("SKU-PULSES", "STORE-SF", 100, 14),
        ("SKU-PULSES", "STORE-DAL", 104, 14),
        ("SKU-PULSES", "ONLINE", 170, 14),
        ("SKU-FLOUR", "DC-EAST", 350, 14),
        ("SKU-FLOUR", "DC-WEST", 290, 14),
        ("SKU-FLOUR", "STORE-NY", 120, 14),
        ("SKU-FLOUR", "STORE-SF", 108, 14),
        ("SKU-FLOUR", "STORE-CHI", 112, 14),
        ("SKU-FLOUR", "ONLINE", 180, 14),
        ("SKU-GHEE", "DC-EAST", 170, 14),
        ("SKU-GHEE", "DC-WEST", 150, 14),
        ("SKU-GHEE", "STORE-NY", 70, 14),
        ("SKU-GHEE", "STORE-SF", 62, 14),
        ("SKU-GHEE", "STORE-DAL", 66, 14),
        ("SKU-GHEE", "ONLINE", 140, 14),
        ("SKU-OLIVE-OIL", "DC-EAST", 160, 14),
        ("SKU-OLIVE-OIL", "DC-WEST", 130, 14),
        ("SKU-OLIVE-OIL", "STORE-NY", 80, 14),
        ("SKU-OLIVE-OIL", "STORE-SF", 70, 14),
        ("SKU-OLIVE-OIL", "STORE-CHI", 68, 14),
        ("SKU-OLIVE-OIL", "ONLINE", 150, 14),
        ("SKU-HONEY", "DC-EAST", 150, 14),
        ("SKU-HONEY", "DC-WEST", 120, 14),
        ("SKU-HONEY", "STORE-NY", 76, 14),
        ("SKU-HONEY", "STORE-SF", 68, 14),
        ("SKU-HONEY", "STORE-DAL", 66, 14),
        ("SKU-HONEY", "ONLINE", 140, 14),
        ("SKU-DRIED-FRUIT", "DC-EAST", 160, 14),
        ("SKU-DRIED-FRUIT", "DC-WEST", 140, 14),
        ("SKU-DRIED-FRUIT", "STORE-NY", 84, 14),
        ("SKU-DRIED-FRUIT", "STORE-SF", 76, 14),
        ("SKU-DRIED-FRUIT", "STORE-CHI", 72, 14),
        ("SKU-DRIED-FRUIT", "ONLINE", 150, 14),
        ("SKU-ORANGE-JUICE", "STORE-NY", 170, 14),
        ("SKU-ORANGE-JUICE", "STORE-SF", 150, 14),
        ("SKU-ORANGE-JUICE", "STORE-CHI", 140, 14),
        ("SKU-ORANGE-JUICE", "STORE-DAL", 136, 14),
        ("SKU-ORANGE-JUICE", "ONLINE", 220, 14),
        ("SKU-SPARKLING", "STORE-NY", 200, 14),
        ("SKU-SPARKLING", "STORE-SF", 180, 14),
        ("SKU-SPARKLING", "STORE-CHI", 168, 14),
        ("SKU-SPARKLING", "STORE-DAL", 160, 14),
        ("SKU-SPARKLING", "ONLINE", 250, 14),
        ("SKU-COLD-BREW", "STORE-NY", 130, 14),
        ("SKU-COLD-BREW", "STORE-SF", 118, 14),
        ("SKU-COLD-BREW", "STORE-CHI", 110, 14),
        ("SKU-COLD-BREW", "STORE-DAL", 108, 14),
        ("SKU-COLD-BREW", "ONLINE", 190, 14),
        ("SKU-TRAIL-MIX", "STORE-NY", 120, 14),
        ("SKU-TRAIL-MIX", "STORE-SF", 108, 14),
        ("SKU-TRAIL-MIX", "STORE-CHI", 100, 14),
        ("SKU-TRAIL-MIX", "STORE-DAL", 98, 14),
        ("SKU-TRAIL-MIX", "ONLINE", 180, 14),
        ("SKU-CHIPS", "STORE-NY", 190, 14),
        ("SKU-CHIPS", "STORE-SF", 178, 14),
        ("SKU-CHIPS", "STORE-CHI", 170, 14),
        ("SKU-CHIPS", "STORE-DAL", 165, 14),
        ("SKU-CHIPS", "ONLINE", 250, 14),
        ("SKU-COOKIES", "STORE-NY", 160, 14),
        ("SKU-COOKIES", "STORE-SF", 148, 14),
        ("SKU-COOKIES", "STORE-CHI", 140, 14),
        ("SKU-COOKIES", "STORE-DAL", 136, 14),
        ("SKU-COOKIES", "ONLINE", 220, 14),
        ("SKU-GRANOLA", "STORE-NY", 140, 14),
        ("SKU-GRANOLA", "STORE-SF", 130, 14),
        ("SKU-GRANOLA", "STORE-CHI", 124, 14),
        ("SKU-GRANOLA", "STORE-DAL", 120, 14),
        ("SKU-GRANOLA", "ONLINE", 200, 14),
        ("SKU-DETERGENT", "STORE-NY", 100, 14),
        ("SKU-DETERGENT", "STORE-SF", 92, 14),
        ("SKU-DETERGENT", "STORE-CHI", 88, 14),
        ("SKU-DETERGENT", "STORE-DAL", 84, 14),
        ("SKU-DETERGENT", "ONLINE", 170, 14),
        ("SKU-DISH-SOAP", "STORE-NY", 94, 14),
        ("SKU-DISH-SOAP", "STORE-SF", 88, 14),
        ("SKU-DISH-SOAP", "STORE-CHI", 84, 14),
        ("SKU-DISH-SOAP", "STORE-DAL", 82, 14),
        ("SKU-DISH-SOAP", "ONLINE", 160, 14),
        ("SKU-PAPER-TOWEL", "STORE-NY", 110, 14),
        ("SKU-PAPER-TOWEL", "STORE-SF", 102, 14),
        ("SKU-PAPER-TOWEL", "STORE-CHI", 98, 14),
        ("SKU-PAPER-TOWEL", "STORE-DAL", 94, 14),
        ("SKU-PAPER-TOWEL", "ONLINE", 180, 14),
        ("SKU-SOAP", "STORE-NY", 130, 14),
        ("SKU-SOAP", "STORE-SF", 120, 14),
        ("SKU-SOAP", "STORE-CHI", 114, 14),
        ("SKU-SOAP", "STORE-DAL", 110, 14),
        ("SKU-SOAP", "ONLINE", 190, 14),
    ]
    return [
        SaleRecord(sku, location_id, qty=qty, days=days) for sku, location_id, qty, days in rows
    ]
